name: khono_recruit_frontend
description: Full Flutter frontend for KhonoRecruit app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  fl_chart: ^0.55.2
  syncfusion_flutter_charts: ^31.1.19
  http: ^1.1.0
  dio: ^5.0.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.3.2
  vector_math: ^2.1.4
  file_picker: ^8.1.2  # Use the latest version
  flutter_secure_storage: ^9.1.0 
  glassmorphism: ^2.0.0
  lottie: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_bg.jpg
    - assets/images/about_us.png
    - assets/images/register_bg.jpg
    - assets/images/landing_bg.jpg
    - assets/animations/landing_animation.json
    - assets/animations/applications.json
    - assets/animations/interview.json
    - assets/animations/profile.json
    - assets/animations/jobs.json
    - assets/animations/reports.json
    - assets/animations/password.json
    - assets/animations/profile (1).json
