name: khono_recruite
description: A recruitment app with modern red & white UI and authentication flow.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  syncfusion_flutter_charts: ^31.2.4
  flutter_web_auth: ^0.6.0
  percent_indicator: ^4.2.5
  dio: ^5.9.0
  open_file: ^3.5.10
  dotted_border: ^3.1.0
  url_launcher: ^6.3.2
  syncfusion_flutter_calendar: ^31.1.19
  flutter_staggered_animations: ^1.1.0
  table_calendar: ^3.1.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.9.1
  image_picker: ^1.2.0
  web_socket_channel: ^3.0.3
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  google_sign_in: ^7.2.0
  lottie: ^3.3.1
  go_router: ^16.2.4
  fl_chart: ^1.1.0
  vector_math: ^2.1.4
  file_picker: ^10.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - assets/images/bg1.jpg
    - assets/images/bg.jpg
    - assets/images/bg2.jpg
    - assets/images/bg3.jpeg
    - assets/images/bg4.jpg
    - assets/images/bg4.jpg
    - assets/images/client0.png
    - assets/images/client1.png
    - assets/images/client2.png
    - assets/images/client3.png
    - assets/images/client4.png
    - assets/images/client5.png
    - assets/images/logo2.png
    - assets/images/logo3.png
    - assets/images/logo.png
    - assets/images/icon.png
    - assets/images/team0.jpg
    - assets/images/team1.jpg
    - assets/images/team2.jpg
    - assets/images/team3.jpg
    - assets/images/team4.jpg
    - assets/images/team5.jpg
    - assets/icons/Linkedin1.png
    - assets/icons/Linkedin.png
    - assets/icons/Instagram1.png
    - assets/icons/Instagram.png
    - assets/icons/facebook.png
    - assets/icons/facebook1.png
    - assets/icons/x1.png
    - assets/icons/YouTube1.png
    - assets/icons/YouTube.png
    - assets/icons/pbi.png
    - assets/images/
    - Khono_Assets2/images/
    - Khono_Assets2/images/frame_1.jpg
    - Khono_Assets2/Khono_Icon/
    - Khono_Assets2/Khono_Icon/Project Launch_Start/Project Launch_Start_Red Badge_White.png
    - Khono_Assets2/Khono_Icon/Calendar_Date Picker/Calendar_Date Picker_Red.png
    - Khono_Assets2/Khono_Icon/Approved_Tick/Approved_Red.png
    - Khono_Assets2/Khono_Icon/Upload_Arrow/Upload Arrow_Red.png
    - Khono_Assets2/Khono_Icon/Upload_Arrow/Upload Arrow_Red Badge_White.png
    - Khono_Assets2/Khono_Icon/Business Growth_Development/Growth_Development_Red Badge_White.png
    - Khono_Assets2/Khono_Icon/Account_User Profile/red_user_profile.png
    - Khono_Assets2/Khono_Icon/Account_User Profile/User Profile_White Badge_Red.png
    - Khono_Assets2/Khono_Icon/Information_Detail/Information_Red Badge_White.png
    - Khono_Assets2/Khono_Icon/Login_Lock/Lock_Red Badge_White.png
    - Khono_Assets2/Khono_Icon/Logout/Logout_Red Badge_White.png
    - Khono_Assets2/Khono_Icon/AI Chatbot_Red Badge_White.png
    - Khono_Assets2/Khono_Icon/Send_Paper Plane/Send_Paper Plane_Red.png
